<?php
session_start();
include('database.php');
include('Razorpay.php'); // Include Razorpay API keys

// Check if the user is logged in
if (!isset($_SESSION['user_id'])) {
    $_SESSION['error_message'] = "You need to log in first.";
    header("Location: login.php");
    exit;
}

$user_id = $_SESSION['user_id'];
$username = $_SESSION['username'];

// Fetch the user's cart items from the database
$query = "SELECT p.name, p.price, c.quantity, (p.price * c.quantity) AS total_price 
          FROM cart c
          JOIN products p ON c.product_id = p.id
          WHERE c.user_id = $user_id";
$cart_items = $conn->query($query);

// Calculate the total amount
$total_amount = 0;
if ($cart_items && $cart_items->num_rows > 0) {
    while ($item = $cart_items->fetch_assoc()) {
        $total_amount += $item['total_price'];
    }
} else {
    $_SESSION['error_message'] = "Your cart is empty.";
    header("Location: index.php");
    exit;
}

// Initialize Razorpay Order
$razorpayOrderData = [
    'amount' => $total_amount * 100, // Razorpay accepts amount in paise (1 INR = 100 paise)
    'currency' => 'INR',
    'payment_capture' => 1
];

// Create the order using Razorpay API
$api = new Razorpay\Api\Api($key_idrzp_test_VVaxe8RQLNF0DS, $sd8RA3Y3y1LMsKoqPzuyoIn4); // Razorpay API credentials

try {
    $razorpayOrder = $api->orders->create($razorpayOrderData);
    $orderId = $razorpayOrder->id;
} catch (Exception $e) {
    $_SESSION['error_message'] = "Error creating payment order: " . $e->getMessage();
    header("Location: payment.php");
    exit;
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script> <!-- Razorpay Checkout Script -->
</head>
<body>
    <div class="container mt-5">
        <h2>Payment Information</h2>
        <?php if (isset($_SESSION['error_message'])) { echo '<div class="alert alert-danger">' . $_SESSION['error_message'] . '</div>'; unset($_SESSION['error_message']); } ?>
        
        <!-- Display Cart Items -->
        <h3>Your Cart</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if ($cart_items && $cart_items->num_rows > 0) {
                    while ($item = $cart_items->fetch_assoc()) {
                        echo '<tr>
                                <td>' . htmlspecialchars($item['name']) . '</td>
                                <td>$' . htmlspecialchars($item['price']) . '</td>
                                <td>' . htmlspecialchars($item['quantity']) . '</td>
                                <td>$' . htmlspecialchars($item['total_price']) . '</td>
                              </tr>';
                    }
                }
                ?>
            </tbody>
        </table>

        <h4>Total Amount: ₹<?php echo number_format($total_amount, 2); ?></h4>

        <!-- Razorpay Payment Button -->
        <button id="razorpay-button" class="btn btn-success">Pay Now</button>

        <script>
            var options = {
                "key": "<?php echo $key_id; ?>", // Razorpay API Key
                "amount": "<?php echo $razorpayOrder->amount; ?>", // Amount in paise
                "currency": "INR",
                "name": "Your Store",
                "description": "Payment for Order",
                "image": "https://example.com/logo.png",
                "order_id": "<?php echo $orderId; ?>", // Order ID generated by Razorpay
                "handler": function (response) {
                    // Send payment details to the server
                    var paymentDetails = {
                        razorpay_payment_id: response.razorpay_payment_id,
                        razorpay_order_id: response.razorpay_order_id,
                        razorpay_signature: response.razorpay_signature
                    };
                    
                    // Send payment details to server (payment_process.php)
                    var xhr = new XMLHttpRequest();
                    xhr.open("POST", "payment_process.php", true);
                    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                    xhr.send("payment_details=" + JSON.stringify(paymentDetails));

                    xhr.onload = function () {
                        if (xhr.status == 200) {
                            alert("Payment Successful!");
                            window.location.href = "order_confirmation.php";
                        } else {
                            alert("Payment failed. Please try again.");
                        }
                    };
                },
                "prefill": {
                    "name": "<?php echo $username; ?>",
                    "email": "<?php echo $_SESSION['email']; ?>",
                    "contact": "<?php echo $_SESSION['contact']; ?>"
                },
                "theme": {
                    "color": "#F37254"
                }
            };
            
            var rzp1 = new Razorpay(options);
            
            document.getElementById('razorpay-button').onclick = function(e) {
                rzp1.open();
                e.preventDefault();
            }
        </script>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
